#!/bin/bash

# agenda
# (projeto agenda telefonica 'Cadeira de ShellScript' - segundo semestre 2013)

listar() {
clear
sort lista_ag | nl | more -d
menu
}

##############################################################
adicionar() { #Adiciona nomes na agenda
clear
echo "Digite o nome do contato:*"
read name

while [ -z "$name" ]
  do
    if [ -z "$name" ]; then
      echo "Este campo é obrigatório."
      read -p "Deseja voltar? Digite o nome ou 'S' para sair: " -n 1 -r # Essa maravilha aqui nao requer Enter para confirmar
          if [[ $REPLY =~ ^[Ss]$ ]]
            then
              clear
              menu
            else
              read name
          fi
    fi
done
  echo "Digite o número do telefone:*"
  read num_tel #Adiciona números na agenda
while [ -z "$num_tel" ]
   do
      if [ -z "$num_tel" ]; then
        echo "Este campo é obrigatório"
        read -p "Deseja voltar? Digite o número ou 'S' para sair: " -n 1 -r
            if [[ $REPLY =~ ^[Ss]$ ]]
            then
              clear
              menu
            else
              read num_tel
      fi
fi
done
clear
echo  $name $num_tel >> lista_ag
echo "#####################################"
echo "####  O contato foi adicionado.  ####"
echo "#####################################"
menu
}

procurar() {
clear
echo "Digite o nome ou número que deseja procurar"
echo "Você pode digitar parte do nome ou número"
read pesquisa
# sed = lista_ag #retorna a agenda
grep --ignore-case -e $pesquisa lista_ag | sort | nl
menu
}

editar() {
echo "Desculpe, função indisponível no momento."
}

apagar() {
clear
sort lista_ag | nl
echo "Pressione Shift+PgUp ou Shift+PgDn para ver a lista"
echo "Qual a linha deseja deletar?"
read deletar
while [ -z $deletar ]
 do
echo "Você não escreveu nada"
  echo "Você pode pressionar Ctrl+c para cancelar"

if [ -z $deletar ]
 then
echo "Digite o número da linha"
 read deletar
fi
done

if [[ "$deletar" =~ (^[0-9]{1,3}?$) ]]
 then
	echo "A linha número $deletar foi apagada"
	echo "A nova agenda é:"
touch . lista.tmp
	sort lista_ag | sed -e $deletar'd'| sort > lista.tmp
mv lista.tmp lista_ag
sort lista_ag | nl
echo "Pressione Shift+PgUp ou Shift+PgDn para ver a nova lista"

else
	echo "Ops! Você não digitou um número ou um número elevado."
fi
menu
}

# VErifica se existe um arquivo chamado lista_ag, senão cria-o.
if [ -f lista_ag ]; then
clear
else
clear
touch . lista_ag
fi

menu(){
select opcao in "Listar agenda" "Agendar" "Procurar" "Editar" "Apagar" "Fechar"
  do
     case $opcao in
    "Listar agenda")
    	listar;;
    "Agendar")
    	adicionar;;
    "Procurar")
    	procurar;;
    "Editar")
    	editar;;
    "Apagar")
    	apagar;;
    "Fechar")
    	exit;;
        *)
      echo "Escolha não disponível";;
      esac
    done
}
menu
